[tool.poetry]
name = "pyrecest"
description = "Framework for recursive Bayesian estimation in Python."
readme = "README.md"
authors = ["Florian Pfaff <pfaff@kit.edu>"]
version = "0.5.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "*"
scipy = "^1.11.3"
matplotlib = "*"
mpmath = "*"
filterpy = "*"
pyshtools = "*"
beartype = "*"
numpy-quaternion = "*"
shapely = "*"
torch = { version = "2.1.0+cpu", optional = true, markers = "extra == 'pytorch_cpu_support'" }
torchvision = { version = "*", optional = true, markers = "extra == 'pytorch_cpu_support'" }
torchaudio = { version = "2.1.0+cpu", optional = true, markers = "extra == 'pytorch_cpu_support'" }

[tool.poetry.extras]
healpy_support = ["healpy"]
pytorch_cpu_support = ["torch", "torchvision", "torchaudio"]
pytorch_cpu_support = []

[tool.poetry.group.dev.dependencies]
healpy = "*"
autopep8 = "^2.0.2"
pytest = "*"
parameterized = "*"