name: Trigger Test After Megalinter

on:
  workflow_run:
    workflows: ["MegaLinter"]  # Name of the MegaLinter workflow
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Trigger Test Workflow
      run: |
        curl -X POST \
             -H "Authorization: Bearer ${{ secrets.PAT }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/actions/workflows/tests.yml/dispatches" \
             -d '{"ref":"${{ github.event.workflow_run.head_branch }}"}'
