---
    # MegaLinter GitHub Action configuration file
    # More info at https://megalinter.io
    name: TriggerTest
    
    permissions:
      checks: write
      pull-requests: write
      contents: write
    
    on: # yamllint disable-line rule:truthy
      # Trigger mega-linter at every push. Action will also be visible from Pull Requests to main
      push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
      pull_request:
        branches: [master, main]
    
    env: # Comment env block if you do not want to apply fixes
      # Apply linter fixes configuration
      APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
      APPLY_FIXES_EVENT: pull_request # Decide which event triggers application of fixes in a commit or a PR (pull_request, push, all)
      APPLY_FIXES_MODE: commit # If APPLY_FIXES is used, defines if the fixes are directly committed (commit) or posted in a PR (pull_request)
    
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    
    jobs:
      build:
        name: MegaLinter
        runs-on: ubuntu-latest
    
        permissions:
          checks: write
          pull-requests: write
          contents: write
    
        steps:
          - name: Trigger Test Workflow
            run: |
              curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.PAT }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/workflows/tests.yml/dispatches" \
                    -d '{"ref":"${{ env.sha }}"}'
          - name: Trigger Test Workflow
            run: |
              curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.PAT }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/workflows/tests.yml/dispatches" \
                    -d '{"ref":"${{ steps.get_sha.outputs.sha }}"}'
          - name: Trigger try
            run: |
              curl -X POST \
              -H "Authorization: Bearer ${{   secrets.PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/tests.yml/dispatches" \
              -d '{"ref":"${{ github.head_ref }}"}'