name: Update requirements.txt

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

jobs:
  update_requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: refs/heads/main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install --upgrade poetry

      - name: Install project dependencies
        run: poetry install

      - name: Update requirements.txt
        run: poetry export --format requirements.txt --output requirements.txt --extras healpy_support --without-hashes

      - name: Update requirements_dev.txt
        run: poetry export --dev --format requirements.txt --output requirements_dev.txt --without-hashes

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b update-requirements
          git add .
          git commit -m "Update requirements.txt"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update requirements.txt"
          title: "Update requirements.txt"
          body: "Updates the requirements.txt"
          branch: "update-requirements"
